/* Generated by scripts/themes.mjs. Do not edit by hand. */
export const THEME_NAMES = ["Lime","Fern","Jade","Teal","Aqua","Sky","Azure","Cobalt","Indigo","Violet","Orchid","Magenta","Rose","Crimson","Rust","Amber","Olive"] as const;
export const THEME_GROUNDS = ["#0d2117","#07211d","#062123","#092028","#0f1f2b","#161d2d","#1d1b2c","#221a2a","#271826","#2a1820","#2c171a","#2c1814","#2a190e","#261b0b","#211d0a","#1b1f0c","#142011"] as const;
export const THEME_COUNT = 17;
