#!/usr/bin/env python3
"""Regenerate src/content/nav.ts from the H2 headings in each page."""
import re, os

PAGES = [
    ("/", "src/app/page.tsx", "Index", "Home", "index"),
    ("/work/curbnturf", "src/app/work/curbnturf/page.tsx", "01", "CurbNTurf", "case"),
    ("/work/coqui-cardboard", "src/app/work/coqui-cardboard/page.tsx", "02", "Coqui Cardboard", "case"),
    ("/work/large-print-books", "src/app/work/large-print-books/page.tsx", "03", "Large Print Books + LRS", "case"),
    ("/about", "src/app/about/page.tsx", "—", "About", "page"),
]

def slug(t):
    t = t.replace("‘", "").replace("’", "")
    t = re.sub(r"[^a-zA-Z0-9\s-]", "", t)
    return re.sub(r"\s+", "-", t.strip().lower())[:60]

out = ["/* Generated by `npm run nav` from the H2 headings in each page.",
       "   The command palette and the section rail both read from this. */",
       "",
       "export type Section = { id: string; title: string };",
       "export type Page = {",
       "  href: string;",
       "  number: string;",
       "  label: string;",
       '  kind: "index" | "case" | "page";',
       "  sections: Section[];",
       "};",
       "",
       "export const pages: Page[] = ["]

for href, path, num, label, kind in PAGES:
    heads = []
    if os.path.exists(path):
        src = open(path).read()
        heads = [re.sub(r"\s+", " ", h.strip())
                 for h in re.findall(r"<H2>\s*([^<]+?)\s*</H2>", src, re.S)]
    out += ["  {", f'    href: "{href}",', f'    number: "{num}",',
            f'    label: "{label}",', f'    kind: "{kind}",']
    if heads:
        out.append("    sections: [")
        for h in heads:
            out.append(f'      {{ id: "{slug(h)}", title: "{h}" }},')
        out.append("    ],")
    else:
        out.append("    sections: [],")
    out.append("  },")

out += ["];", "",
        'export const caseOrder = pages.filter((p) => p.kind === "case").map((p) => p.href);',
        ""]

open("src/content/nav.ts", "w").write("\n".join(out))
print("src/content/nav.ts regenerated")
