/* Generated by `npm run nav` from the H2 headings in each page.
   The command palette and the section rail both read from this. */

export type Section = { id: string; title: string };
export type Page = {
  href: string;
  number: string;
  label: string;
  kind: "index" | "case" | "page";
  sections: Section[];
};

export const pages: Page[] = [
  {
    href: "/",
    number: "Index",
    label: "Home",
    kind: "index",
    sections: [],
  },
  {
    href: "/work/curbnturf",
    number: "01",
    label: "CurbNTurf",
    kind: "case",
    sections: [
      { id: "three-people-and-a-platform-that-was-barely-working", title: "Three people and a platform that was barely working" },
      { id: "one-decision-shaped-every-screen-after-it", title: "One decision shaped every screen after it" },
      { id: "designing-inside-the-thing-we-shipped", title: "Designing inside the thing we shipped" },
      { id: "a-ranch-is-not-a-house", title: "A ranch is not a house" },
      { id: "what-the-numbers-actually-say", title: "What the numbers actually say" },
      { id: "version-two", title: "Version two" },
      { id: "the-apps", title: "The apps" },
    ],
  },
  {
    href: "/work/coqui-cardboard",
    number: "02",
    label: "Coqui Cardboard",
    kind: "case",
    sections: [
      { id: "let-me-be-upfront-about-this-one", title: "Let me be upfront about this one" },
      { id: "why-nineties-cards", title: "Why nineties cards" },
      { id: "four-vaults-four-reasons", title: "Four vaults, four reasons" },
      { id: "two-ways-in", title: "Two ways in" },
      { id: "the-look-is-the-argument", title: "The look is the argument" },
      { id: "the-parts-that-were-hard", title: "The parts that were hard" },
      { id: "what-it-was-part-of", title: "What it was part of" },
    ],
  },
  {
    href: "/work/infocon-lrs",
    number: "03",
    label: "InfoCon + LRS",
    kind: "case",
    sections: [
      { id: "a-website-from-2003-and-an-owner-who-knew-exactly-what-he-wa", title: "A website from 2003 and an owner who knew exactly what he was doing" },
      { id: "the-reader-is-almost-never-the-buyer", title: "The reader is almost never the buyer" },
      { id: "what-large-print-means-when-youre-the-one-making-it", title: "What large print means when you’re the one making it" },
      { id: "the-decision-two-brands-on-purpose", title: "The decision: two brands, on purpose" },
      { id: "the-part-that-isnt-a-website", title: "The part that isn’t a website" },
      { id: "the-argument-i-lost", title: "The argument I lost" },
      { id: "where-it-stands", title: "Where it stands" },
    ],
  },
  {
    href: "/about",
    number: "—",
    label: "About",
    kind: "page",
    sections: [
      { id: "inside-my-own-work-since-2018", title: "Inside my own work since 2018" },
      { id: "i-design-and-i-build", title: "I design and I build" },
      { id: "the-tink-tank", title: "The Tink Tank" },
      { id: "printed-on-cardboard", title: "Printed on cardboard" },
    ],
  },
];

export const caseOrder = pages.filter((p) => p.kind === "case").map((p) => p.href);
